[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

# Allow Stripe to render securely on the order page only
[[headers]]
  for = "/order"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://js.stripe.com https://m.stripe.network; connect-src 'self' https://api.stripe.com https://m.stripe.network; frame-src https://js.stripe.com https://hooks.stripe.com https://m.stripe.network;"
