[build]
  command = ""           # Skip the build step
  publish = "/"          # Root directory for your static files
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"  # Ensures your serverless function runs smoothly
